### ISSUE TITLE
Index ACF fields

### ISSUE THREAD

**Issue by MaximeCulea** [BeAPI/bea-find-media#21]
Add ACF support : https://github.com/BeAPI/bea-find-media/blob/master/classes/admin/main.php#L71

**Comment by herewithme** [comment]
Done : https://github.com/BeAPI/bea-find-media/commit/1b3ab10e0a2cd6196380330ab92b828b8c1035ca

@MaximeCulea 
But, I think you should validate the validity of the IDs provided by the filter:
bea.find_media.post.index

For example, I know that I refer randomly to media IDs or other types of content.
I can possibly do a check in my method, but I think it should take place after the hook.

**Comment by herewithme** [comment]
First draft implementation : https://github.com/BeAPI/bea-find-media/pull/22

**Comment by MaximeCulea** [comment]
Thx for the job !

And you damn right, I thought about it yesterday night while I implemented Gallery and links, because they could not be internal files, but was too late to implement it ^^
Anyway, let's continue talking about this into #22.

Can we close here the #21 ? @herewithme

**Comment by herewithme** [comment]
Yep !
