### ISSUE TITLE
Force indexation (wp-cli)

### ISSUE THREAD

**Issue by MaximeCulea** [BeAPI/bea-find-media#4]

**Comment by MaximeCulea** [comment]
Check if it works : https://github.com/BeAPI/bea-find-media/blob/master/classes/wp-cli/index-site.php#L16

**Comment by Rahe** [comment]
Not working, you need to instancitate the class with the hooks before lauching the command

**Comment by MaximeCulea** [comment]
You mean loading all the plugin ?
I thought that in wp-cli, plugins where loaded, isn't it ?

**Comment by MaximeCulea** [comment]
### _Note for me :_
Try using `runcommand` for launching itself equivalent commands :
`$return = \WP_CLI::runcommand( sprintf( 'core update-db --network --url=%s%s', $network->domain, $network->path ), array( 'return' => true ) );`

**Comment by MaximeCulea** [comment]
@Rahe it will also autoload all dependencies as helper and so on ?

**Comment by MaximeCulea** [comment]
Working now !

**Comment by MaximeCulea** [comment]
`wp bea_find_media index_site --url={url}`
